# Generated by Django 5.2.4 on 2025-07-12 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_price_alter_item_status_alter_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaprequest',
            name='offered_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offered_swaps', to='core.item'),
        ),
    ]
